# These are supported funding model platforms

github: [thisisdayal]
patreon: # Replace with a single Patreon username
open_collective: thisisdayal
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: thisisdayal
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.buymeacoffee.com/thisisdayal']
